name: deploy to prod

on:
  push:
    branches: workspace_publish
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/synapse-workspace-deployment@release-1.0
    with:
      TargetWorkspaceName: 'training-prod'
      TemplateFile: './training-git/TemplateForWorkspace.json'
      ParametersFile: './training-git/TemplateParametersForWorkspace.json'
      OverrideArmParameters: './training-git/parameters.yaml'
      environment: 'Azure Public'
      resourceGroup: 'rg-training-git'
      clientId: ${{secrets.CLIENTID_TRAINING}}
      clientSecret:  ${{secrets.CLIENTSECRET_TRAINING}}
      subscriptionId: '53305064-9303-4225-8b70-d93b4348d68c'
      tenantId: '2e2e9ce3-5a7c-4387-a907-d3f9bfe4e389'
      DeleteArtifactsNotInTemplate: 'true'
      managedIdentity: 'False'
